### ISSUE TITLE
cloudasr/web image fails apt-get

### ISSUE THREAD

**Issue by jfainberg** [UFAL-DSG/cloud-asr#17]
Error below. Worked by adding apt-get update. Not sure if it's a local issue to me. If not I can do a PR.

> E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/mysql-common_5.5.46-0ubuntu0.14.04.2_all.deb  404  Not Found [IP: 91.189.88.161 80]
> FROM ufaldsg/cloud-asr-base
> 
> E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/libmysqlclient18_5.5.46-0ubuntu0.14.04.2_amd64.deb  404  Not Found [IP: 91.189.88.161 80]
> 
> E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mysql-5.5/libmysqlclient-dev_5.5.46-0ubuntu0.14.04.2_amd64.deb  404  Not Found [IP: 91.189.88.161 80]
> 
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by choko** [comment]
Fixed in 08e3c2e9ed670efa3099b465afd3d69caafa61c0
